---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: true
      name: Managed Prometheus
      type: prometheus
      url: https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-e25de7e4-c5b8-4768-a344-e5cb91155df3/api/v1/query
      jsonData:
        sigV4Auth: true
        sigV4Region: us-east-1
        sigV4AuthType: default
